'use client';
import { useEffect, useRef, useState } from 'react';import Image from 'next/image';
import { Lightbox, type LightboxItem } from '@/components/portfolio/shared/Lightbox';
import s from './CurrentRenders.module.css';
const renders:LightboxItem[]=[
 {src:'/images/renders/01 - Living.webp',w:1086,h:1448,alt:'Casa Ángel: render actual del living'},
 {src:'/images/renders/03 - Acceso.webp',w:941,h:1672,alt:'Casa Ángel: render actual del acceso'},
 {src:'/images/renders/14 - Estructura.webp',w:941,h:1672,alt:'Casa Ángel: hormigón visto y madera en el patio'},
 {src:'/images/renders/13 - Hall.webp',w:1448,h:1086,alt:'Casa Ángel: hall central, volumen curvo y escalera iluminada'}
];
export function CurrentRenders(){const [open,setOpen]=useState<number|null>(null);const root=useRef<HTMLElement>(null),hall=useRef<HTMLElement>(null);
useEffect(()=>{const el=hall.current;if(!el)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){el.dataset.entered='true';return;}const io=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){el.dataset.entered='true';io.disconnect();}},{threshold:.35});io.observe(el);return()=>io.disconnect();},[]);
useEffect(()=>{const el=root.current;if(!el)return;let raf=0;const update=()=>{raf=0;const r=el.getBoundingClientRect();const p=matchMedia('(prefers-reduced-motion: reduce)').matches?1:Math.max(0,Math.min(1,(64-r.top)/Math.max(1,r.height-innerHeight)));el.style.setProperty('--material-progress',String(p));el.style.setProperty('--text-opacity',String(Math.max(0,1-p*3)));el.style.setProperty('--text-blur',String(Math.min(16,p*40))+'px');el.querySelectorAll('figure').forEach((figure,i)=>(figure as HTMLElement).style.setProperty('--reveal',String(Math.max(0,Math.min(1,(p-i*.2)*5)))));};const schedule=()=>{if(!raf)raf=requestAnimationFrame(update);};update();window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);return()=>{cancelAnimationFrame(raf);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);};},[]);return <>
<section id="renders-actuales" ref={root} className={s.section} data-chapter="Casa Ángel · Renders actuales"><div className={s.materialFrame}><header><div className="sec-label">Del anteproyecto al proyecto</div><h2 className="sec-title">Honestidad<br/><em>material.</em></h2><p>La madera aporta la calidez del refugio; el hormigón, resistencia y presencia. Los materiales se muestran como son, y la luz permite recorrer sus texturas. Estas decisiones del anteproyecto permanecen en el proyecto actual.</p></header><div className={s.gallery}>{renders.slice(0,3).map((r,i)=><figure key={r.src} className={s.figure} style={{'--arrival':String(i*.2)} as React.CSSProperties}><button onClick={()=>setOpen(i)} aria-label={'Ampliar: '+r.alt}><Image src={r.src} alt={r.alt} width={r.w} height={r.h} sizes="(max-width:768px) 90vw, 42vw" loading="lazy"/></button><figcaption><span>0{i+1}</span>{['El living / La calidez de la madera','El acceso / Entre interior y exterior','El patio / La presencia del hormigón'][i]}</figcaption></figure>)}</div></div></section>
<section id="hall-central" ref={hall} className={s.hall} data-chapter="Casa Ángel · Hall central"><div><div className="sec-label">El hall central</div><h2 className="sec-title">El corazón<br/><em>de la casa.</em></h2><p>El hall central reúne las dos alas y articula el recorrido entre los niveles. Es un lugar de encuentro que da continuidad a la vida de la casa.</p><p>El volumen curvo acompaña la llegada y suaviza el paso entre los espacios. La escalera iluminada continúa ese recorrido: hormigón, madera y luz vuelven a encontrarse en el centro del refugio.</p></div><button onClick={()=>setOpen(3)} aria-label="Ampliar el render del hall y la escalera"><Image src={renders[3].src} alt={renders[3].alt} width={1448} height={1086} sizes="(max-width:768px) 90vw, 78vw"/></button></section>

<Lightbox items={renders} index={open} onChange={setOpen}/></>;}

export function ProjectDevelopment(){return <section id="desarrollo-proyecto" className={s.next} data-chapter="Casa Ángel · Desarrollo del proyecto"><div className="sec-label">El proyecto / Próxima mirada</div><h2 className="sec-title">De la experiencia<br/><em>al detalle.</em></h2><p>Instalaciones y documentación del proyecto.</p><span className={s.pending}>Contenido en preparación</span></section>;}
